language: ruby

services:
  - docker

env:
  matrix:
    - TAG=v1
    - TAG=v2
    - TAG=v3
    - TAG=v4
    - TAG=v5
    - TAG=v6
    - TAG=v7
    - TAG=v8

before_script:
  - DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
  - echo ${DIR}

script:
  - echo "${DIR}"/"${TAG}/"
  - echo "${DIR}/${TAG}/"
  - ls ${DIR}
  - docker build -t stephenneal/certbot-nginx:${TAG} "${DIR}"/"${TAG}/"

after_script:
  - docker images
