language: ruby

services:
  - docker

env:
  global:
    - secure: aaCM8vNRCg3HQ8Ue7hwIxEviHzwfsxgjYrUflWHQPlsBfDjW/xTevUN4obisSEwiCH5/8yZtnGU2s0Buld7iVqqEGAxf/gRS5O1mQgmsBtI29WJfT43hx1Aa9E6waoUQ8T6i+vJ/WTEtR1rzLbzhCGaU0o+cSwCI1IpKrJ1vzvEliv2fIzpufrkr19e5T+NEJrsgyx5BgCpp6iVYS3D0y8W89d9YOMUqouYDJPFjByVJiiQA+14mqIUgXnH97/m4is9BsZmHqWWtwoblqpzQ9XUhHIZtzZTKCZbNHrVwn8asL77c3O/ZdQiMBD9cp6SDDXCqwNcF2aGU+WWrr7iu9eSDIE3zLwhizFFX6G4sbdLb1BD4P2meiK9Ex316yHohlyqs3+daXU0JuTk5bEZZXhgb3oygB5EriN8mRQRr5b4jmPVEoZggNabZY7xbnPLyfxLqDONLGNKEXxoBy/hYdj1u0lM8S1kRRu7sKCLphdY3RjynPdxQcYOqMq4wl5up0XXfaqpOQI4amqhy6pzwm9tcOd8J/E+/PxjxsWiERMoCINfOk9UNqPb/nSGbjzrSHHAEagw+Lv0A7Z/JbmPmOLkAd89KKgfFkHP9jtiJVktbIDpToX0KZzxgwoCW5MdutkxGGy0CubF5hJFzM5wxxhsy66nxBtowhQJ86qesGao=
    - secure: Fo2x+UvfWCw0Uk2wMKlAs6X0BhG7YYy7zGlSyO824oHbSNWobsQE4sBFCRlgLS7oqms0PFjy61ZJqCZysMVpQyYghDnIgx8JHSmG7rTtBtRd+UFZgL6Tg/Jw3zyXxjMomLMuMTvxHNATb5qiJSV7kS4pz15KUXaa8BCyxo6auzqa08gcAtKCMwUqHeCb7nLm0Qgiw6LBIiU8VXx0kvHTiLKhPfk/ObrySrOD3gZX51eS1c2AxhQrJmIniuiEixmv2nS27nQMRt6a/Zx6EZO8fYSi6F6GzbbyyGEx4GMkPnjW/lXjwgMddzgYyrBR+GBha/0hPYRVaGYVBKIsiXsbQvAgFqZI4SS3cLASub9aP//WB7j/vKqokzKvdVVFBd2n6kUYDOzShlr/KQU7EmT15xEWNSe+q+Qx+5BKappvyj04TXJ8EjIFaVxFV5Yf4croBrG7A4k3ocPcH5su98zZqhM2KZA8w/GBi58QZUzoub0vg+GZx86i/b874TYHmVFVGTY1kKzWgOUWyF8iRa/lxa/d2Ozft/pZ1FS//hI+pjKuv72q0Sa1M1HUsV0ftRZ+yhXzFE03AZLzK2EhDNue7f16L6P2CG9jbtQBFWYCIPUEv3shR3AY2W0/8PXifztuWQrEgQeIaQXuFnKZ+bAb2mrv8yRHBFZZAS9RucnxiXI=

  matrix:
    - TAG=v10
    - TAG=v9
    - TAG=v8
    - TAG=v7
    - TAG=v6
    - TAG=v5
    - TAG=v4
    - TAG=v3
    - TAG=v2
    - TAG=v1

before_script:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

script:
  - sh build.sh "${TAG}"

after_script:
  - docker images

deploy:
  provider: script
  script: sh push.sh "${TAG}"
  on:
    tags: true